config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show, :edit, :update] do
  end

  resources :tasks

  resources :followed_users, only: [:index]
  resources :followers, only: [:index]

  resources :relationships, only: [:create, :destroy]

  resources :blogs do
    resources :comments

   collection do
      post :confirm
    end
  end

 resources :contacts, only: [:new, :create] do
   collection do
      post :confirm
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  resources :submit_requests do
      get 'inbox', on: :collection
      member do
        patch 'approve'
        patch 'reject'
      end
    end

  resources :conversations do
    resources :messages
  end


  root 'top#index'

end

app/models/submit_request.rb
class SubmitRequest < ActiveRecord::Base

  belongs_to :user
  belongs_to :task
  belongs_to :request_user, class_name: 'User', foreign_key: 'request_user_id'

  validates :user_id, :task_id, :request_user_id, presence: true
  validate :no_repeated_request, on: :create

  enum status: {依頼中:"1", 承諾:"2", 却下:"9"}


  private

   def no_repeated_request
     submit_request = SubmitRequest.where(task_id: task_id, status: 1)
     errors.add(:base, "このタスクは既に依頼をだしています") unless submit_request.blank?
   end

end

app/controllers/submit_requests_controller.rb
class SubmitRequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_submit_request, only: [:show, :edit, :update, :destroy, :approve, :reject]

  def index
  @submit_requests = SubmitRequest.where(user_id: current_user.id)
  end

  def show
  end

  def new
    @submit_request = current_user.submit_requests.build
  end

  def edit
  end

  def create
    @submit_request = current_user.submit_requests.build(submit_request_params)

    respond_to do |format|
      if @submit_request.save
        format.html { redirect_to @submit_request, notice: 'タスク依頼が作成されました！' }
        format.json { render :show, status: :created, location: @submit_request }
      else
        format.html { render :new }
        format.json { render json: @submit_request.errors, status: :unprocessable_entity }
      end
     end
   end

  def inbox
    @submit_requests = SubmitRequest.where(request_user_id: current_user.id).where(status: 1)
  end

  def update
    respond_to do |format|
      if @submit_request.update(submit_request_params)
        format.html { redirect_to submit_requests_path, notice: '依頼をを更新しました' }
        format.json { render :show, status: :ok, location: @submit_request }
      else
        format.html { render :edit }
        format.json { render json: @submit_request.errors, status: :unprocessable_entity }
      end
    end
  end

    def destroy
    @submit_request.destroy
    respond_to do |format|
      format.html { redirect_to submit_requests_path, notice: '依頼を削除しました' }
      format.json { head :no_content }
      end
   end

    def approve
        if @submit_request.update(submit_request_params)
          @submit_request.task.update(charge_id: current_user.id)
          redirect_to inbox_submit_requests_path, notice: '依頼を承認しました。'
        else
          redirect_to inbox_submit_requests_path, notice: '不具合が発生しました、もう一度操作を行ってください'
        end
      end


    def reject
     if @submit_request.update(submit_request_params)
       redirect_to inbox_submit_requests_path, notice: '依頼を却下しました。'
     else
       redirect_to inbox_submit_requests_path, notice: '不具合が発生しました、もう一度操作を行ってください。'
     end
    end

private
  def set_submit_request
    @submit_request = SubmitRequest.find(params[:id])
  end

  def submit_request_params
  params.require(:submit_request).permit(:user_id, :task_id, :title,:message, :content, :deadline, :charge_id, :status, :request_user_id)
  end

end

app/helpers/submit_requests_helper.rb
module SubmitRequestsHelper
end

app/views/submit_requests/_form.html.erb
<%= form_for(@submit_request) do |f| %>
  <% if @submit_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submit_request.errors.count, "error") %> により依頼できません</h2>

      <ul>
      <% @submit_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% f.hidden_field :user_id %>

 <div class="field">
   <%= f.label :task_id %><br>
   <%= f.collection_select :task_id, Task.where(charge_id: current_user.id), :id, :title %>
 </div>
 <div class="field">
   <%= f.label :メッセージ %><br>
   <%= f.text_area :message %>
 </div>
 <div class="field">
   <%= f.label :request_user_id %><br>
   <%= f.collection_select :request_user_id, User.where.not(id: current_user.id), :id, :name %>
 </div>
 <div class="field">
   <%= f.label :status %><br>
   <%= f.select :status, SubmitRequest.statuses.keys %>
 </div>
 <div class="actions">
   <%= f.submit %>
 </div>
<% end %>

app/views/submit_requests/edit.html.erb
<h1>依頼タスクの編集</h1>

<%= render 'form' %>

<%= link_to '詳細', @submit_request %> |
<%= link_to '戻る', submit_requests_path %>

app/views/submit_requests/inbox.html.erb
<p id="notice"><%= notice %></p>

<h1>依頼されているタスク一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>依頼者</th>
      <th>タスク</th>
      <th>メッセージ</th>
      <th>依頼者id</th>
      <th>ステータス</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submit_requests.each do |submit_request| %>
      <tr>
        <td><%= submit_request.user.name %></td>
        <td><%= submit_request.task.title %></td>
        <td><%= submit_request.message %></td>
        <td><%= submit_request.request_user_id %></td>
        <td><%= submit_request.status %></td>
        <td><%= link_to '詳細', submit_request %></td>
        <td><%= link_to '承認する', approve_submit_request_path(submit_request, submit_request: {status: 2}), method: :patch, data: { confirm: '承認しますか?' } %></td>
        <td><%= link_to '却下する', reject_submit_request_path(submit_request, submit_request: {status: 9}), method: :patch, data: { confirm: '却下しますか?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'タスクの依頼', new_submit_request_path %>

app/views/submit_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>依頼一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>名前</th>
      <th>タスク</th>
      <th>メッセージ</th>
      <th>依頼先</th>
      <th>ステータス</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submit_requests.each do |submit_request| %>
      <tr>
        <td><%= submit_request.user.name %></td>
        <td><%= submit_request.task.title %></td>
        <td><%= submit_request.message %></td>
        <td><%= submit_request.request_user.name %></td>
        <td><%= submit_request.status %></td>
        <td><%= link_to '詳細', submit_request %></td>
        <td><%= link_to '編集', edit_submit_request_path(submit_request) %></td>
        <td><%= link_to '削除', submit_request, method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'タスク依頼の新規作成', new_submit_request_path %>

app/views/submit_requests/new.html.erb
<h1>タスク依頼の作成</h1>

<%= render 'form' %>

<%= link_to '戻る', submit_requests_path %>

app/views/submit_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>名前</strong>
  <%= @submit_request.user.name %>
</p>

<p>
  <strong>タスク</strong>
  <%= @submit_request.task.title %>
</p>

<p>
  <strong>メッセージ</strong>
  <%= @submit_request.message %>
</p>

<p>
  <strong>依頼者</strong>
  <%= @submit_request.request_user_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @submit_request.status %>
</p>

<%= link_to '編集', edit_submit_request_path(@submit_request) %> |
<%= link_to '戻る', submit_requests_path %>